name: Yarn
on:
  pull_request:
    branches:
      - renovate/**
jobs:
  yarn_lock_changes:
    name: Lock File Changes
    runs-on: ubuntu-latest
    # Permission overwrite is required for Dependabot PRs
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Digest Lock File
        uses: Simek/yarn-lock-changes@5b249bcbb9794145fefa43a2a8330b884697e40f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          collapsibleThreshold: 25
          failOnDowngrade: false
          path: yarn.lock
          updateComment: true
